NEUTRAL_BYTE = 0x55

DATA_SOURCE_PIN_0 	= 0 # 16 bit public data provided by Pin 0
DATA_SOURCE_PIN_1 	= 1 # 16 bit public data provided by Pin 1
DATA_SOURCE_PIN_2 	= 2 # 16 bit public data provided by Pin 2
DATA_SOURCE_PIN_3 	= 3 # 16 bit public data provided by Pin 3
DATA_SOURCE_PIN_4 	= 4 # 16 bit public data provided by Pin 4
DATA_SOURCE_PIN_5 	= 5 # 16 bit public data provided by Pin 5
DATA_SOURCE_PIN_6 	= 6 # 16 bit public data provided by Pin 6
DATA_SOURCE_PIN_7 	= 7 # 16 bit public data provided by Pin 7
DATA_SOURCE_PIN_8 	= 8 # 16 bit public data provided by Pin 8
DATA_SOURCE_PIN_9 	= 9 # 16 bit public data provided by Pin 9
DATA_SOURCE_PIN_10 	= 10 # 16 bit public data provided by Pin 10
DATA_SOURCE_PIN_11 	= 11 # 16 bit public data provided by Pin 11
DATA_SOURCE_PIN_12 	= 12 # 16 bit public data provided by Pin 12
DATA_SOURCE_PIN_13 	= 13 # 16 bit public data provided by Pin 13
DATA_SOURCE_PIN_14 	= 14 # 16 bit public data provided by Pin 14
DATA_SOURCE_PIN_15 	= 15 # 16 bit public data provided by Pin 15
DATA_SOURCE_PIN_16 	= 16 # 16 bit public data provided by Pin 16
DATA_SOURCE_PIN_17 	= 17 # 16 bit public data provided by Pin 17
DATA_SOURCE_PIN_18 	= 18 # 16 bit public data provided by Pin 18
DATA_SOURCE_PIN_19 	= 19 # 16 bit public data provided by Pin 19
DATA_SOURCE_INCREMENTING_NUMBER 	= 65 # An number that increments each time it is accessed.
DATA_SOURCE_1024mvCounts 	= 66 # The number of ADC counts that result from a 1.024V reading
DATA_SOURCE_FRAMES_RUN_LSW 	= 67 # The number of frames run since reset, least significant 16 bits
DATA_SOURCE_FRAMES_RUN_MSW 	= 68 # The number of frames run since reset, most significant 16 bits
DATA_SOURCE_OVERRUN_FRAMES 	= 69 # The number of frames that ran more than 1mS
DATA_SOURCE_TEMPERATURE 	= 70 #The internal core temperature expressed in 100ths deg C
DATA_SOURCE_PACKETS_RECEIVED 	= 71 # The nubmer of incoming CMD packets that have been processed since reset rolls over at 65535 #
DATA_SOURCE_ERRORS 	= 72 #The number of incoming packets that have caused errors since reset rolls over at 65535 #
DATA_SOURCE_DROPPED_FRAMES 	= 73 # The number of times since reset that a frame ran so far behind that it crossed two subsequent 1ms boundaries, causing a permanent lost frame
DATA_SOURCE_SYSTEM_UTILIZATION 	= 74 # A number between 0 and 65535 that scales to the average length of pin processing frames between 0 and 1000mS
DATA_SOURCE_VCC_mVOLTS 	= 75 # The system source voltage in mV
DATA_SOURCE_VBG_COUNTS_VS_VREF 	= 76 # A/D conversion of VBG against VRef . Used for mfg calibration
DATA_SOURCE_LFSR 	= 78 # A Linear Feedback Shift Register that produces a Pseudo random sequence of 16 bit values
DATA_SOURCE_PIN_0_MV 	= 100 # Pin 0 public output expressed in mV for analog modes only #
DATA_SOURCE_PIN_1_MV 	= 101 # Pin 1 public output expressed in mV for analog modes only #
DATA_SOURCE_PIN_2_MV 	= 102 # Pin 2 public output expressed in mV for analog modes only #
DATA_SOURCE_PIN_3_MV 	= 103 # Pin 3 public output expressed in mV for analog modes only #
DATA_SOURCE_PIN_4_MV 	= 104 # Pin 4 public output expressed in mV for analog modes only #
DATA_SOURCE_PIN_16_MV 	= 116 # Pin 16 public output expressed in mV for analog modes only #
DATA_SOURCE_PIN_17_MV 	= 117 # Pin 17 public output expressed in mV for analog modes only #
DATA_SOURCE_PIN_18_MV 	= 118 # Pin 18 public output expressed in mV for analog modes only #
DATA_SOURCE_PIN_19_MV 	= 119 # Pin 19 public output expressed in mV for analog modes only #
DATA_SOURCE_2HZ_SQUARE 	= 164 # Square wave that alternates between 0 and 65535 every 256 frames
DATA_SOURCE_2HZ_SAW 	= 165 # Sawtooth wave that goes from 0 to 65535 to 0 every 512 frames
DATA_SOURCE_1HZ_SQUARE 	= 167 # Square wave that alternates between 0 and 65535 every 512 frames
DATA_SOURCE_1HZ_SAW 	= 168 # Sawtooth wave that goes from 0 to 65535 to 0 every 1024 frames
DATA_SOURCE_2SEC_SQUARE 	= 170 #Square wave that alternates between 0 and 65535 every 1024 frames
DATA_SOURCE_2SEC_SAW 	= 171 #Sawtooth wave that goes from 0 to 65535 to 0 every 2048 frames
DATA_SOURCE_8SEC_SQUARE 	= 173 #Square wave that alternates between 0 and 65535 every 4096 frames
DATA_SOURCE_8SEC_SAW 	= 174 #Sawtooth wave that goes from 0 to 65535 to 0 every 8192 frames
DATA_SOURCE_65SEC_SQUARE 	= 176 # Square wave that alternates between 0 and 65535 every 32768 frames
DATA_SOURCE_65SEC_SAW 	= 177  #Sawtooth wave that goes from 0 to 65535 to 0 every 65536 frames

PIN_MODE_DIGITAL_IO = 0
PIN_MODE_CONTROLLED = 1
PIN_MODE_ANALOG_INPUT = 2
PIN_MODE_SERVO = 3
PIN_MODE_THROUGHPUT_CONSUMER = 4
PIN_MODE_QUADRATURE_ENC = 5
PIN_MODE_WATCHDOG = 7
PIN_MODE_PROTECTEDOUTPUT = 8
PIN_MODE_DEBOUNCE = 10
PIN_MODE_TM1637 = 11
PIN_MODE_MODEWS2812 = 12
PIN_MODE_SW_UART = 13
PIN_MODE_INPUT_PROCESSOR = 14
PIN_MODE_MATRIX_KEYPAD = 15
PIN_MODE_PWM = 16
PIN_MODE_PULSE_TIMER = 18
PIN_MODE_UART_TXRX = 17
PIN_MODE_FRAME_TIMER = 21
PIN_MODE_SW18AB_CAPTOUCH = 22
PIN_MODE_UART1_RX_TX = 23
PIN_MODE_RESISTANCEINPUT = 24
PIN_MODE_PULSE_ON_CHANGE = 25
PIN_MODE_HS_SERVO = 26
PIN_MODE_ULTRASONIC_DISTANCE = 27
PIN_MODE_LIQUIDCRYSTAL = 28
PIN_MODE_UNKNOWN = 0xFF

PIN_STATE_LOW = 0
PIN_STATE_HIGH = 1
PIN_STATE_INPUT = 2

CMD_ECHO 	= '!'
CMD_READ_BUFFER_ASCII 	= 'G'
CMD_ASCII_SET_PIN 	= 'P'
CMD_RESET 	= 'R'
CMD_SET_BUFFER_ASCII 	= 'S'
CMD_RESYNC 	= 'U'
CMD_VERSION 	= 'V'
CMD_SUPPLYVOLTAGE 	= 'v'
CMD_BINARY_READ_PIN_BUFFFER 	= 0x81
CMD_BINARY_SET_PIN_BUFFFER 	= 0x82
CMD_BINARY_READ_USER_BUFFER 	= 0x83
CMD_BINARY_WRITE_USER_BUFFER 	= 0x84
CMD_BINARY_WRITE_USER_BUFFER_CONTINUE 	= 0x85
CMD_BINARY_QUEUE_INITIALIZE 	= 0x90
CMD_BINARY_QUEUE_ADD_BYTES 	= 0x91
CMD_BINARY_QUEUE_ADD_7BYTES 	= 0x92
CMD_BINARY_QUEUE_READ_BYTES 	= 0x93
CMD_BINARY_QUEUE_INFORMATION 	= 0x94
CMD_BINARY_CFG 	= 0x9F
CMD_BINARY_READ_RAM 	= 0xA0
CMD_BINARY_READ_FLASH 	= 0xA1
CMD_BINARY_READ_EEPROM 	= 0xA2
CMD_BINARY_WRITE_RAM 	= 0xA3
CMD_BINARY_WRITE_FLASH 	= 0xA4
CMD_CALIBRATE_ANALOG 	= 0xA5
CMD_ENABLE_2ND_UART 	= 0xA6
CMD_READ_LAST_ERROR_PACKET 	= 0xA7
CMD_UART0_TX_7BYTES 	= 0xB0
CMD_UART0_RX_7BYTES 	= 0xB1
CMD_UART1_TX_7BYTES 	= 0xB2
CMD_UART1_RX_7BYTES 	= 0xB3
CFG_PIN_MODE0 	= 200
CFG_PIN_MODE1 	= 201
CFG_PIN_MODE2 	= 202
CFG_PIN_MODE3 	= 203
CFG_PIN_MODE4 	= 204
CFG_PIN_MODE5 	= 205
CFG_PIN_MODE6 	= 206
CFG_PIN_MODE7 	= 207
CFG_PIN_MODE8 	= 208
CFG_PIN_MODE9 	= 209
CFG_PIN_MODE10 	= 210
CFG_PIN_OUTPUTSCALE 	= 210
CFG_PIN_INPUTPROCESS 	= 211
CFG_PIN_MODE_HW_0 	= 220
CFG_CHANNEL_MODE_HW_1 	= 221
CFG_CHANNEL_MODE_HW_2 	= 222
CFG_CHANNEL_MODE_HW_3 	= 223